FROM node:20.16.0-alpine3.20

# Add a non-root user
RUN addgroup -S app && adduser -S -G app app

# Set work directory
WORKDIR /usr/src/app

# Copy package files and install pnpm as root
COPY package.json pnpm-lock.yaml ./

# Install pnpm globally as root
RUN npm i -g pnpm

# Configure pnpm store directory
RUN pnpm config set store-dir /usr/src/app/.pnpm-store

# Install dependencies as non-root user
RUN pnpm install

# Ensure proper permissions for the .next directory
RUN mkdir -p /usr/src/app/.next && chown -R app:app /usr/src/app/.next

# Switch to the non-root user
USER app

# Copy application source code
COPY --chown=app:app . ./

# Expose the port
EXPOSE 3000

# Set the default command
CMD ["pnpm", "run", "dev"]