version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: template_nextjs_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    # command: npm run dev

  server-node:
    build:
      context: ./server-node
      dockerfile: Dockerfile.dev
    container_name: template_nodejs_server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server-node:/usr/src/app
    # command: npm run dev