version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: template_nextjs_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
      - D:/pnpm-store:/usr/src/app/pnpm-store

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: template_nodejs_server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
      - D:/pnpm-store:/usr/src/app/pnpm-store
volumes:
  client_node_modules:
  backend_node_modules: