import type { Metadata } from 'next'
import ReduxProvider from './redux/provider'
import { ApolloWrapper } from './graphql/apollo-wrapper'
import Header from './components/Header/Header'

// import fonts
import { Inter } from 'next/font/google'

// import stylesheets
import './globals.css'


export const metadata: Metadata = {
    title: 'Next app',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="">
                <ApolloWrapper>
                    <ReduxProvider>
                        <Header />
                        <main className='titi-font max-container'>
                            {children}
                        </main>
                    </ReduxProvider>
                </ApolloWrapper>
            </body>
        </html>
    )
}