FROM node:20.16.0-alpine3.20

# Add a non-root user
RUN addgroup -S app && adduser -S -G app app

# Set work directory
WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN npm i -g pnpm nodemon

# Configure pnpm store directory
RUN pnpm config set store-dir /usr/src/app/.pnpm-store

# Install dependencies as non-root user
RUN pnpm install

COPY . ./

EXPOSE 5000

ENV PORT=5000

CMD ["pnpm", "run", "dev"]