# air.toml

# Root directory of the project
root = "."

# Build command and binary location
[build]
cmd = "go build -o tmp/main ."  # Command to build your application and place the binary in the tmp folder
bin = "tmp/main"                # Path to the binary file

# Watch configuration
[watch]
exclude = [
  "vendor/**",
  "test/**",
  "*test",
  "*.tmp",
  "*.log"
]
include = [
  "**/*.go",
  "config/**",
  "templates/**"
]

delay = 200   # 200ms delay before restarting the application

# Log configuration
[log]
time = "2006-01-02 15:04:05"   # Custom time format for log timestamps

# Display log output
[logger]
time = true
