name: Testing golang backend

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
        - 'server-golang/**'
    pull_request:
        branches:
            - main
        paths:
        - 'server-golang/**'
jobs:
    test:
        name: Testing golang backend
        runs-on: ubuntu-latest

        steps:
          - name: Set up envirnment vairables
            run: |
              echo "ENV=continuous_integration" >> $GITHUB_ENV
              echo "PORT=4000" >> $GITHUB_ENV
              echo "TIMEZONE=Africa/Lagos" >> $GITHUB_ENV
              echo "DB_NAME=template_test_db" >> $GITHUB_ENV
              echo "POSTGRES_DB_USER=${{ secrets.POSTGRES_DB_USER }}" >> $GITHUB_ENV
              echo "POSTGRES_DB_PASSWORD=${{ secrets.POSTGRES_DB_PASSWORD }}" >> $GITHUB_ENV
              echo "POSTGRES_DB_PORT=5432" >> $GITHUB_ENV
              echo "POSTGRES_DB_TIMEZONE=Africa/Lagos" >> $GITHUB_ENV
              echo "MYSQL_DB_USER=${{ secrets.MYSQL_DB_USER }}" >> $GITHUB_ENV
              echo "MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}" >> $GITHUB_ENV
              echo "MYSQL_DB_PORT=3306" >> $GITHUB_ENV
              echo "MYSQL_DB_TIMEZONE=Africa/Lagos" >> $GITHUB_ENV
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
              echo "JWT_TIME_1=7" >> $GITHUB_ENV
              echo "JWT_TIME_2=365" >> $GITHUB_ENV
              env
              exit 1

          - name: Check out code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v4
            with:
                go-version: 1.22.2

          - name: Install Docker
            run: |
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo systemctl start docker
              sudo systemctl enable docker
              docker --version

          - name: Install dependencies
            run: go mod download
            working-directory: server-golang

          - name: Run tests
            run: go test -v ./...
            working-directory: server-golang
