name: Testing golang backend

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
        - 'server-golang/**'
    pull_request:
        branches:
            - main
        paths:
        - 'server-golang/**'
jobs:
    test:
        name: Testing golang backend
        runs-on: ubuntu-latest
        env:
          ENV: continuous_integration
        steps:
          - name: Check out code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v4
            with:
                go-version: 1.22.2

          - name: Log environment variables and exit
            run: |
              echo "Logging environment variables..."
              env
              echo "$ENV"
              exit 0  # Exit successfully (change to `exit 1` if you want to fail the job)

          - name: Install Docker
            run: |
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo systemctl start docker
              sudo systemctl enable docker
              docker --version

          - name: Install dependencies
            run: go mod download
            working-directory: server-golang

          - name: Run tests
            run: go test -v ./...
            working-directory: server-golang
